[package]
name = "sortinghat-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "sortinghat"
path = "src/bin/sortinghat.rs"

[[bin]]
name = "sortinghatd"
path = "src/bin/sortinghatd.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
sortinghat-core = { path = "../sortinghat-core", version = "=0.1.0" }
sortinghat-service = { path = "../sortinghat-service", version = "=0.1.0" }
thiserror.workspace = true
uuid.workspace = true
rustix.workspace = true

[dev-dependencies]
sortinghat-fs = { path = "../sortinghat-fs", version = "=0.1.0" }

[lints]
workspace = true
