[package]
name = "sortinghat-service"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
sortinghat-core = { path = "../sortinghat-core", version = "=0.1.0" }
sortinghat-agent = { path = "../sortinghat-agent", version = "=0.1.0" }
sortinghat-fs = { path = "../sortinghat-fs", version = "=0.1.0" }
sortinghat-journal = { path = "../sortinghat-journal", version = "=0.1.0" }
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
